### PR TITLE
billsImage & rideImage

### PR DESCRIPTION
**Pull request by shivanishivalenka**
1. added imageController.js
2.  fixed styling in generalRequestConfirm screen. 
3. paymentPreference in general request is now a List instead of string.

### CODE REVIEW

**Comment by bsaikiran618** [comment]
@shivanishivalenka I made some changes, please resolve the conflicts in this PR

**Comment by shivanishivalenka** [comment]
@bsaikiran618 conflicts are resolved. Once check before merging.

**Comment by bsaikiran618** [comment]
@shivanishivalenka In the finish delivery endpoint, add the image paths to the requestDoc document. This should be done in the same place where we are updating the request status to "RIDER CONFIRMED"

**Comment by shivanishivalenka** [comment]
@bsaikiran618, I actually did it, but it was overwritten after the conflicts. I updated it now once check it out :)

**Pull request merged**
